repos:
  # 🐍 Python: Linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff
        name: Ruff Linter
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        name: Ruff Formatter
        types_or: [python, pyi, jupyter]

  # ⚡ Biome: JS/TS/JSON/CSS/etc.
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.0.0-beta.5
    hooks:
      - id: biome-check
        name: Biome Lint & Format
        additional_dependencies: ["@biomejs/biome@1.9.4"]
        # ✅ Languages: JS, TS, JSX, TSX, JSON, JSONC, CSS, GraphQL

  # ✨ Prettier: Markdown & HTML (other files handled by Biome)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        name: Prettier (Markdown & HTML)

  # 🌙 StyLua: Lua formatter
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.1.0
    hooks:
      - id: stylua
        name: StyLua Formatter

  # 🧾 Dasel: YAML and JSON schema/structure validator
  - repo: https://github.com/TomWright/dasel
    rev: v2.8.1
    hooks:
      - id: dasel-validate
        name: Dasel YAML/JSON Validator
        files: \.(json|yaml|yml)$

  # 🧪 Local fast tests
  - repo: local
    hooks:
      - id: test
        name: Run Fast Tests
        entry: just fast-test
        language: system
        pass_filenames: false
        always_run: true
