#!/bin/zsh

# https://github.com/FelixKratz/JankyBorders/wiki/Man-Page
: <<'run_the_following_with_!w'
. ~/.config/borders/bordersrc

run_the_following_with_!w

local -a border_options=(
	style=round
	width=10.0
	hidpi=on
    active_color=0xff00ff22 # blue (Note this is ARGB)
	inactive_color=0xff414550
)

pkill borders # kill old borders
echo "${border_options[@]}"
borders "${border_options[@]}" &
