#!/bin/zsh

# https://github.com/FelixKratz/JankyBorders/wiki/Man-Page

local -a border_options=(
	style=round
	width=10.0
	hidpi=on
	active_color=0xffffff0000 # NOTE: Color Starts with transp
	inactive_color=0xff414550
)

pkill borders # kill old borders
echo "${border_options[@]}"
borders "${border_options[@]}" &
